"use client";

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'fr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => any;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('fr');

  const translations: any = {
    fr: {
      nav_title: "BIONOOR — Présentation · Marché & opportunité d’investissement",
      hero_title: "BIONOOR",
      hero_subtitle: "Bio premium depuis plus de 20 ans",
      hero_description: "BIONOOR est une marque éthique ancrée depuis plus de 20 ans dans l’alimentation bio, fondée autour des valeurs humaines de son dirigeant.",
      problem_subtitle: "Le Problème",
      problem_title: "Une demande forte, une offre peu lisible.",
      problem_intro: "Le marché bio + traçabilité manque de marques fortes et lisibles.",
      problem_item1_title: "Origine floue :",
      problem_item1_desc: "Difficulté à tracer la provenance réelle des produits.",
      problem_item2_title: "Traçabilité limitée :",
      problem_item2_desc: "Manque de transparence sur la chaîne de production.",
      problem_item3_title: "Qualité variable :",
      problem_item3_desc: "Constance de qualité souvent aléatoire.",
      opportunity_subtitle: "Opportunité",
      opportunity_title: "Marché des dattes et du Bio en croissance en Europe.",
      opp_card1_title: "Croissance du marché des dattes : environ 5% / an",
      opp_card1_desc: "La consommation de dattes en Europe progresse constamment, portée par l’intérêt pour les aliments naturels, bio et énergétiques. Les importations augmentent chaque année, reflétant une demande dynamique. En France, plusieurs milliers de tonnes de dattes sont consommées annuellement, avec un marché retail estimé à plus de 100 millions d’euros pour les dattes conditionnées. Les données observées indiquent une dynamique positive de la demande, avec une croissance annuelle moyenne d’environ 4–5 %, particulièrement marquée autour de périodes culturelles comme le Ramadan.",
      opp_card2_title: "Croissance du marché des dattes Bio : environ 6% / an",
      opp_card2_desc: "La demande de dattes bio croît en Europe, portée par l’intérêt croissant des consommateurs pour les aliments naturels, sains et certifiés. Les importations de dattes biologiques vers l’UE augmentent. En France, une part croissante des dattes consommées est issue de l’agriculture biologique. Le segment bio représente une part significative du marché retail des dattes conditionnées (estimé à plus de 100 millions d’euros), avec une progression régulière observée au cours des dernières années. Les données de marché indiquent une dynamique soutenue pour les dattes bio, avec une croissance annuelle moyenne observée autour de 4–6 %.",
      competition_title: "Concurrence & espace de marché (dattes bio)",
      competition_text: "Le marché des dattes est fragmenté et majoritairement occupé par des produits conventionnels. Le segment bio, bien qu’en croissance, reste peu structuré et dominé par des acteurs de petite taille, sans marque leader clairement identifiée à l’échelle européenne.",
      risks_title: "Risques identifiés & défis du marché des dattes BIO",
      risk1_title: "Approvisionnement & climat",
      risk1_text: "Dépendance aux récoltes (conditions climatiques, rendements variables, aléas agricoles).",
      risk2_title: "Qualité, bio & conformité",
      risk2_text: "Maintenir une qualité constante, des certifications fiables and des process contrôlés à chaque étape.",
      risk3_title: "Logistique, stockage & coûts",
      risk3_text: "Contraintes de transport international, conservation des produits, variations des coûts d’importation.",
      risk4_title: "Pression concurrentielle sur les prix",
      risk4_text: "Concurrence d’acteurs low-cost, importateurs peu différenciés and produits de qualité inégale.",
      risk5_title: "Saisonnalité de la demande",
      risk5_text: "Forte concentration des ventes sur certaines périodes (ex : Ramadan), nécessité d’anticiper les volumes and les stocks.",
      risk6_title: "Risque réglementaire & administratif",
      risk6_text: "Évolutions des normes (bio, import, traçabilité), contraintes douanières and contrôles sanitaires.",
      phase1_subtitle: "Phase 1",
      phase1_title: "Les Dattes : Notre produit d'entrée",
      phase1_quality: "Notation qualité 18,2/20 (experts)",
      phase1_desc: "Produit B2B existant depuis 20 ans with une identité algérienne forte. Le bio est rare sur ce segment, ce qui nous confère un avantage compétitif majeur.",
      phase1_formats: "Formats : boîtes famille, coffrets premium, cadeaux B2B.",
      phase1_recurrence: "Produit à forte récurrence.",
      targets_subtitle: "Cibles",
      targets_title: "Quels consommateurs pour Bionoor ?",
      target1_title: "Cible principale",
      target1_text: "Familles musulmanes résidant en France et en Europe à la recherche de produits sains.",
      target2_title: "Cibles secondaires",
      target2_text: "Consommateurs bio non musulmans et collectivités (B2B).",
      target3_title: "Usages",
      target3_text: "Consommation quotidienne, période du Ramadan, et coffrets cadeaux.",
      solution_subtitle: "Notre Solution",
      solution_title: "Bio certifié et conforme par process validé",
      sol1_title: "Notre Solution",
      sol1_text: "Bio certifié et conforme par process validé",
      sol2_title: "Bio certifié",
      sol2_text: "De l’origine Algérie (zones identifiées) jusqu’au consommateur final.",
      sol3_title: "Procédures respectées et validées",
      sol3_text: "Procédures respectées à chaque étape de la chaîne de production.",
      sol4_title: "Qualité & transparence",
      sol4_text: "Produits sains et naturels, qualité constante, transparence totale sur les process.",
      assets_subtitle: "Actifs",
      assets_title: "Un socle déjà solide pour décoller.",
      asset1_title: "10 000",
      asset1_desc: "Emails qualifiés en base.",
      asset2_title: "25 000",
      asset2_desc: "Membres sur Facebook.",
      asset3_title: "B2B",
      asset3_desc: "Référencements historiques collectivités.",
      asset4_title: "Filières",
      asset4_desc: "Sourcing direct Algérie.",
      bm_subtitle: "Business Model",
      bm_title: "Marge brute cible ~50 % (retail).",
      bm_d2c: "D2C e-commerce prioritaire.",
      bm_d2c_desc: "Le canal direct permet de capter la valeur et d'activer la communauté existante.",
      bm_b2b: "B2B existant maintenu pour le volume.",
      bm_rotation: "Rotation rapide des stocks.",
      bm_bfr: "BFR maîtrisé par les précommandes.",
      roadmap_subtitle: "Roadmap",
      roadmap_title: "Une montée en puissance maîtrisée.",
      roadmap_p1_title: "Phase 1 (0–3 mois)",
      roadmap_p1_desc: "Focus dattes only, lancement e-commerce, réactivation base, premières ventes.",
      roadmap_p2_title: "Phase 2 (4–6 mois)",
      roadmap_p2_desc: "Structuration logistique, optimisation prix & formats, offres B2B packagées.",
      roadmap_p3_title: "Phase 3 (6–12 mois)",
      roadmap_p3_desc: "Nouvelles références (chocolat bio, thé bio, café bio, barres de dattes), montée en volume maîtrisée.",
      finance_subtitle: "Financement",
      finance_title: "Besoin de financement : [À compléter]",
      finance_usage: "Utilisation des fonds :",
      fin_item1_title: "Produits & sourcing",
      fin_item2_title: "E-commerce & outils",
      fin_item3_title: "Activation marketing",
      fin_item4_title: "Logistique",
      fin_item5_title: "Sécurité & imprévus",
      finance_objectives: "Objectifs clés :",
      finance_objectives_desc: "Traction B2C, validation marché, décision go/no-go.",
      risk_mitigation_subtitle: "Risques",
      risk_mitigation_title: "Pilotage par la data et mitigation.",
      rm_item1_title: "Risques identifiés",
      rm_item1_desc: "Filières saisonnières, logistique, traction B2C, constance qualité.",
      rm_item2_title: "Actions de mitigation",
      rm_item2_desc: "Diversification progressive, stocks stratégiques courts, tests marché, pilotage par data.",
      team_subtitle: "Équipe",
      team_title: "Une expertise solide.",
      team_direction: "Direction",
      team_hadj: "Hadj Khelil : Sourcing & qualité. Expert bio reconnu.",
      team_resp: "Responsable BIONOOR : Pilotage B2C en interne.",
      team_ops: "Opérations",
      team_ops_desc: "Prestataires spécialisés au départ pour le site, le CRM, la logistique et le marketing pour une agilité maximale.",
      cta_title: "Ce projet n'est pas une promesse, c'est la réactivation structurée d'un actif réel.",
      cta_desc: "Produit déjà validé, marque existante, filières réelles et actifs existants activables. Un financement modeste pour une trajectoire claire vers le cash.",
      cta_button: "Lancer, mesurer, décider",
      footer_copy: "© 2026 BIONOOR. Tous droits réservés.",
      budget_subtitle: "Plan financier",
      budget_title: "Budget & Allocation des fonds",
      budget_intro: "Cette section détaille la structure budgétaire prévue pour le projet BIONOOR. Tous les chiffres sont actuellement en attente de finalisation.",
      budget_investments: "Investissements initiaux",
      budget_table_item: "Poste de dépense",
      budget_table_amount: "Montant",
      budget_item1: "Sourcing & Stock initial",
      budget_item2: "Développement plateforme e-commerce",
      budget_item3: "Marketing & Acquisition",
      budget_item4: "Logistique & Packaging",
      budget_total: "TOTAL BESOIN",
      budget_tobecompleted: "[À compléter]",
      budget_phase_subtitle: "Détail",
      budget_phase_title: "Répartition par phase",
      budget_p1_title: "Phase 1 : Lancement",
      budget_p1_desc: "Focus sur l'acquisition client et la mise en place technique. Allocation : [À compléter] %",
      budget_p2_title: "Phase 2 : Optimisation",
      budget_p2_desc: "Amélioration des process et élargissement de l'offre. Allocation : [À compléter] %",
      budget_p3_title: "Phase 3 : Scale",
      budget_p3_desc: "Augmentation des volumes et diversification. Allocation : [À compléter] %",
      budget_hyp_subtitle: "Note",
      budget_hyp_title: "Hypothèses de calcul",
      budget_hyp1: "Marge brute cible maintenue à [À compléter] %",
      budget_hyp2: "Coût d'acquisition client (CAC) estimé à [À compléter] €",
      budget_hyp3: "Panier moyen visé : [À compléter] €",
      budget_back: "← Retour à la présentation",
      rend_back: "← Retour à la présentation",
      rend_perf_subtitle: "Performances",
      rend_perf_title: "Rendements & Projections",
      rend_perf_intro: "Structure des rendements attendus et projections financières sur 3 ans. Les valeurs chiffrées seront intégrées après validation finale.",
      rend_proj_title: "Projections de Chiffre d'Affaires",
      rend_proj_chart: "Graphique de croissance CA (3 ans)",
      rend_kpi_title: "Indicateurs Clés (KPIs)",
      rend_roi_title: "ROI cible",
      rend_roi_desc: "[À compléter] % sur la période",
      rend_be_title: "Break-even",
      rend_be_desc: "Atteinte du point mort à M+[À compléter]",
      rend_ltv_title: "LTV / CAC",
      rend_ltv_desc: "Ratio visé : [À compléter]",
      rend_sens_subtitle: "Scénarios",
      rend_sens_title: "Analyse de sensibilité",
      rend_scen1_title: "Scénario Conservateur",
      rend_scen1_desc: "Hypothèse de croissance modérée basée sur les actifs existants.",
      rend_scen2_title: "Scénario Médian",
      rend_scen2_desc: "Hypothèse de référence avec activation marketing standard.",
      rend_scen3_title: "Scénario Ambitieux",
      rend_scen3_desc: "Accélération via partenariats et élargissement rapide gamme.",
      rend_dist_subtitle: "Distribution",
      rend_dist_title: "Politique de dividendes",
      rend_dist_text: "La politique de distribution des dividendes sera définie selon les résultats de la Phase 3. Priorité actuelle : Réinvestissement pour croissance organique et sécurisation des filières.",
      rend_dist_quote: "\"Notre objectif est de construire une valeur pérenne et un flux de trésorerie stable pour nos investisseurs.\""
    },
    en: {
      nav_title: "BIONOOR — Presentation · Market & Investment Opportunity",
      hero_title: "BIONOOR",
      hero_subtitle: "Premium organic for over 20 years",
      hero_description: "BIONOOR is an ethical brand rooted for over 20 years in organic food, founded on the human values of its leader.",
      problem_subtitle: "The Problem",
      problem_title: "High demand, low clarity in offerings.",
      problem_intro: "The organic + traceability market lacks strong and clear brands.",
      problem_item1_title: "Unclear origin:",
      problem_item1_desc: "Difficulty in tracing the actual source of products.",
      problem_item2_title: "Limited traceability:",
      problem_item2_desc: "Lack of transparency across the production chain.",
      problem_item3_title: "Variable quality:",
      problem_item3_desc: "Inconsistent quality often at random.",
      opportunity_subtitle: "Opportunity",
      opportunity_title: "Dates and Organic market growing in Europe.",
      opp_card1_title: "Date market growth: around 5% / year",
      opp_card1_desc: "Date consumption in Europe is steadily increasing, driven by interest in natural, organic, and energetic foods. Imports increase every year, reflecting dynamic demand. In France, several thousand tons of dates are consumed annually, with a retail market estimated at over 100 million euros for packaged dates. Observed data indicates a positive demand dynamic, with an average annual growth of about 4-5%, particularly marked around cultural periods like Ramadan.",
      opp_card2_title: "Organic date market growth: around 6% / year",
      opp_card2_desc: "Demand for organic dates is growing in Europe, driven by increasing consumer interest in natural, healthy, and certified foods. Organic date imports to the EU are rising. In France, a growing share of dates consumed comes from organic farming. The organic segment represents a significant share of the retail market for packaged dates (estimated at over 100 million euros), with steady progression observed in recent years. Market data indicates sustained dynamics for organic dates, with an average annual growth observed around 4-6%.",
      competition_title: "Competition & Market Space (organic dates)",
      competition_text: "The date market is fragmented and mostly occupied by conventional products. The organic segment, although growing, remains loosely structured and dominated by small actors, without a clearly identified leading brand at the European scale.",
      risks_title: "Identified Risks & Date Market Challenges (BIO)",
      risk1_title: "Supply & Climate",
      risk1_text: "Dependence on harvests (weather conditions, variable yields, agricultural hazards).",
      risk2_title: "Quality, organic & compliance",
      risk2_text: "Maintain constant quality, reliable certifications and controlled processes at each stage.",
      risk3_title: "Logistics, storage & costs",
      risk3_text: "International transport constraints, product preservation, variations in import costs.",
      risk4_title: "Competitive price pressure",
      risk4_text: "Competition from low-cost actors, poorly differentiated importers and products of uneven quality.",
      risk5_title: "Seasonality of demand",
      risk5_text: "High concentration of sales during certain periods (e.g., Ramadan), need to anticipate volumes and stocks.",
      risk6_title: "Regulatory & administrative risk",
      risk6_text: "Evolving standards (organic, import, traceability), customs constraints and health controls.",
      phase1_subtitle: "Phase 1",
      phase1_title: "Dates: Our entry product",
      phase1_quality: "Quality rating 18.2/20 (experts)",
      phase1_desc: "B2B product existing for 20 years with a strong Algerian identity. Organic is rare in this segment, giving us a major competitive advantage.",
      phase1_formats: "Formats: family boxes, premium boxes, B2B gifts.",
      phase1_recurrence: "High recurrence product.",
      targets_subtitle: "Targets",
      targets_title: "Who are Bionoor's consumers?",
      target1_title: "Primary target",
      target1_text: "Muslim families residing in France and Europe looking for healthy products.",
      target2_title: "Secondary targets",
      target2_text: "Non-Muslim organic consumers and organizations (B2B).",
      target3_title: "Usages",
      target3_text: "Daily consumption, Ramadan period, and gift sets.",
      solution_subtitle: "Our Solution",
      solution_title: "Certified organic & validated process",
      sol1_title: "Our Solution",
      sol1_text: "Certified organic & validated process",
      sol2_title: "Certified Organic",
      sol2_text: "From Algerian origin (identified zones) to the final consumer.",
      sol3_title: "Respected and validated procedures",
      sol3_text: "Procedures respected at every stage of the production chain.",
      sol4_title: "Quality & transparency",
      sol4_text: "Healthy and natural products, constant quality, total transparency on processes.",
      assets_subtitle: "Assets",
      assets_title: "An already solid foundation to take off.",
      asset1_title: "10,000",
      asset1_desc: "Qualified emails in base.",
      asset2_title: "25,000",
      asset2_desc: "Facebook members.",
      asset3_title: "B2B",
      asset3_desc: "Historical institutional listings.",
      asset4_title: "Supply chains",
      asset4_desc: "Direct Algerian sourcing.",
      bm_subtitle: "Business Model",
      bm_title: "Target gross margin ~50% (retail).",
      bm_d2c: "Priority D2C e-commerce.",
      bm_d2c_desc: "Direct channel captures value and activates the existing community.",
      bm_b2b: "Existing B2B maintained for volume.",
      bm_rotation: "Rapid inventory turnover.",
      bm_bfr: "WCR managed through pre-orders.",
      roadmap_subtitle: "Roadmap",
      roadmap_title: "A controlled scale-up.",
      roadmap_p1_title: "Phase 1 (0–3 months)",
      roadmap_p1_desc: "Focus on dates only, e-commerce launch, base reactivation, first sales.",
      roadmap_p2_title: "Phase 2 (4–6 months)",
      roadmap_p2_desc: "Logistics structuring, price & format optimization, packaged B2B offers.",
      roadmap_p3_title: "Phase 3 (6–12 months)",
      roadmap_p3_desc: "New references (organic chocolate, organic tea, organic coffee, date bars), controlled volume growth.",
      finance_subtitle: "Financing",
      finance_title: "Funding requirement: [To be completed]",
      finance_usage: "Use of funds:",
      fin_item1_title: "Products & sourcing",
      fin_item2_title: "E-commerce & tools",
      fin_item3_title: "Marketing activation",
      fin_item4_title: "Logistics",
      fin_item5_title: "Safety & contingencies",
      finance_objectives: "Key objectives:",
      finance_objectives_desc: "B2C traction, market validation, go/no-go decision.",
      risk_mitigation_subtitle: "Risks",
      risk_mitigation_title: "Data-driven management and mitigation.",
      rm_item1_title: "Identified risks",
      rm_item1_desc: "Seasonal supply chains, logistics, B2C traction, quality consistency.",
      rm_item2_title: "Mitigation actions",
      rm_item2_desc: "Progressive diversification, short strategic stocks, market tests, data-driven management.",
      team_subtitle: "Team",
      team_title: "Solid expertise.",
      team_direction: "Management",
      team_hadj: "Hadj Khelil: Sourcing & quality. Recognized organic expert.",
      team_resp: "Organic Manager: Internal B2C management.",
      team_ops: "Operations",
      team_ops_desc: "Specialized service providers initially for the site, CRM, logistics, and marketing for maximum agility.",
      cta_title: "This project is not a promise, it is the structured reactivation of a real asset.",
      cta_desc: "Already validated product, existing brand, real supply chains and activatable existing assets. Modest funding for a clear path to cash.",
      cta_button: "Launch, measure, decide",
      footer_copy: "© 2026 BIONOOR. All rights reserved.",
      budget_subtitle: "Financial Plan",
      budget_title: "Budget & Allocation of Funds",
      budget_intro: "This section details the planned budget structure for the BIONOOR project. All figures are currently pending finalization.",
      budget_investments: "Initial Investments",
      budget_table_item: "Expenditure Item",
      budget_table_amount: "Amount",
      budget_item1: "Sourcing & Initial Stock",
      budget_item2: "E-commerce Platform Development",
      budget_item3: "Marketing & Acquisition",
      budget_item4: "Logistics & Packaging",
      budget_total: "TOTAL REQUIREMENT",
      budget_tobecompleted: "[To be completed]",
      budget_phase_subtitle: "Detail",
      budget_phase_title: "Breakdown by Phase",
      budget_p1_title: "Phase 1: Launch",
      budget_p1_desc: "Focus on customer acquisition and technical setup. Allocation: [To be completed] %",
      budget_p2_title: "Phase 2: Optimization",
      budget_p2_desc: "Process improvement and product range expansion. Allocation: [To be completed] %",
      budget_p3_title: "Phase 3: Scale",
      budget_p3_desc: "Volume increase and diversification. Allocation: [To be completed] %",
      budget_hyp_subtitle: "Note",
      budget_hyp_title: "Calculation Hypotheses",
      budget_hyp1: "Target gross margin maintained at [To be completed] %",
      budget_hyp2: "Estimated Customer Acquisition Cost (CAC) at [To be completed] €",
      budget_hyp3: "Target average basket: [To be completed] €",
      budget_back: "← Back to presentation",
      rend_back: "← Back to presentation",
      rend_perf_subtitle: "Performance",
      rend_perf_title: "Returns & Projections",
      rend_perf_intro: "Structure of expected returns and 3-year financial projections. Numerical values will be integrated after final validation.",
      rend_proj_title: "Revenue Projections",
      rend_proj_chart: "Revenue growth chart (3 years)",
      rend_kpi_title: "Key Indicators (KPIs)",
      rend_roi_title: "Target ROI",
      rend_roi_desc: "[To be completed] % over the period",
      rend_be_title: "Break-even",
      rend_be_desc: "Break-even reached at M+[To be completed]",
      rend_ltv_title: "LTV / CAC",
      rend_ltv_desc: "Target ratio: [To be completed]",
      rend_sens_subtitle: "Scenarios",
      rend_sens_title: "Sensitivity Analysis",
      rend_scen1_title: "Conservative Scenario",
      rend_scen1_desc: "Moderate growth hypothesis based on existing assets.",
      rend_scen2_title: "Median Scenario",
      rend_scen2_desc: "Reference hypothesis with standard marketing activation.",
      rend_scen3_title: "Ambitious Scenario",
      rend_scen3_desc: "Acceleration via partnerships and rapid range expansion.",
      rend_dist_subtitle: "Distribution",
      rend_dist_title: "Dividend Policy",
      rend_dist_text: "The dividend distribution policy will be defined according to the results of Phase 3. Current priority: Reinvestment for organic growth and supply chain security.",
      rend_dist_quote: "\"Our goal is to build sustainable value and a stable cash flow for our investors.\""
    }
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
